'use strict';

define("logTemplateManage.field.model", ['require', 'exports'], function (require, exports) {
    var LogTplManageOriginField = [{
        "id": 1,
        "field": "cdn",
        "name": "厂商标识符",
        "type": "string"
    }, {
        "id": 2,
        "field": "hostname",
        "name": "设备名称",
        "type": "string"
    }, {
        "id": 3,
        "field": "logtype",
        "name": "日志类型",
        "type": "string"
    }, {
        "id": 4,
        "field": "http_cache_layer",
        "name": "服务层级关系",
        "type": "string"
    }, {
        "id": 5,
        "field": "time_local",
        "name": "http日志时间",
        "type": "int"
    }, {
        "id": 6,
        "field": "time_local_second_acc3",
        "name": "http日志时间",
        "type": "double"
    }, {
        "id": 7,
        "field": "time_local_msec",
        "name": "http日志时间",
        "type": "int"
    }, {
        "id": 8,
        "field": "request_time_msec",
        "name": "总时间",
        "type": "int"
    }, {
        "id": 9,
        "field": "request_time_sec",
        "name": "",
        "type": "double"
    }, {
        "id": 10,
        "field": "remote_addr",
        "name": "TCP对端IP",
        "type": "string"
    }, {
        "id": 11,
        "field": "http_x_forwarded_for",
        "name": "X-Forwarded-For",
        "type": "string"
    }, {
        "id": 12,
        "field": "server_addr_server_port",
        "name": "本机IP地址与端口",
        "type": "string"
    }, {
        "id": 13,
        "field": "server_addr",
        "name": "本机IP地址",
        "type": "string"
    }, {
        "id": 14,
        "field": "server_port",
        "name": "本机端口",
        "type": "string"
    }, {
        "id": 15,
        "field": "request_length",
        "name": "接收的客户端请求字节数",
        "type": "int"
    }, {
        "id": 16,
        "field": "host",
        "name": "HOST计费域名",
        "type": "string"
    }, {
        "id": 17,
        "field": "request_method",
        "name": "请求方式",
        "type": "string"
    }, {
        "id": 18,
        "field": "scheme_shost_request_uri",
        "name": "请求url",
        "type": "string"
    }, {
        "id": 19,
        "field": "scheme",
        "name": "",
        "type": "string"
    }, {
        "id": 20,
        "field": "shost",
        "name": "",
        "type": "string"
    }, {
        "id": 21,
        "field": "request_uri",
        "name": "",
        "type": "string"
    }, {
        "id": 22,
        "field": "server_protocol",
        "name": "协议/版本",
        "type": "string"
    }, {
        "id": 23,
        "field": "http_range",
        "name": "Range",
        "type": "string"
    }, {
        "id": 24,
        "field": "sent_http_content_range",
        "name": "Content-Range",
        "type": "string"
    }, {
        "id": 25,
        "field": "http_cache_status_status",
        "name": "cache状态/响应客户端状态",
        "type": "string"
    }, {
        "id": 26,
        "field": "http_cache_status",
        "name": "",
        "type": "string"
    }, {
        "id": 27,
        "field": "status",
        "name": "",
        "type": "string"
    }, {
        "id": 28,
        "field": "http_cache_status_yy",
        "name": "",
        "type": "string"
    }, {
        "id": 29,
        "field": "http_cache_status_num",
        "name": "",
        "type": "int"
    }, {
        "id": 30,
        "field": "server_addr",
        "name": "外网ip",
        "type": "string"
    }, {
        "id": 31,
        "field": "sent_http_content_type",
        "name": "响应数据类型",
        "type": "string"
    }, {
        "id": 32,
        "field": "bytes_sent",
        "name": "发送给客户端的响应字节数",
        "type": "int"
    }, {
        "id": 33,
        "field": "sent_http_content_length",
        "name": "发送给客户端的数据元总大小",
        "type": "int"
    }, {
        "id": 34,
        "field": "upstream_http_x_peer_ip_server_port",
        "name": "回源IP与端口",
        "type": "string"
    }, {
        "id": 35,
        "field": "upstream_http_x_peer_ip",
        "name": "",
        "type": "string"
    }, {
        "id": 36,
        "field": "upstream_server_port",
        "name": "",
        "type": "string"
    }, {
        "id": 37,
        "field": "upstream_status",
        "name": "源站返回HTTP状态码",
        "type": "string"
    }, {
        "id": 38,
        "field": "upstream_first_pkg_time",
        "name": "",
        "type": "int"
    }, {
        "id": 39,
        "field": "upstream_http_x_info_bucketOwner",
        "name": "",
        "type": "string"
    }, {
        "id": 40,
        "field": "upstream_http_x_info_bucketName",
        "name": "",
        "type": "string"
    }, {
        "id": 41,
        "field": "upstream_http_x_info_op",
        "name": "",
        "type": "string"
    }, {
        "id": 42,
        "field": "connection",
        "name": "connection",
        "type": "int"
    }, {
        "id": 43,
        "field": "arg_PNO",
        "name": "维度一(PNO)",
        "type": "string"
    }, {
        "id": 44,
        "field": "upstream_http_server",
        "name": "Server 字段",
        "type": "string"
    }, {
        "id": 45,
        "field": "http_referer",
        "name": "Referer",
        "type": "string"
    }, {
        "id": 46,
        "field": "http_user_agent",
        "name": "User - Agent",
        "type": "string"
    }, {
        "id": 47,
        "field": "http_cookie",
        "name": "cookie",
        "type": "string"
    }, {
        "id": 48,
        "field": "protocol_type",
        "name": "协议类型",
        "type": "string"
    }, {
        "id": 49,
        "field": "ksypreload999",
        "name": "预加载",
        "type": "string"
    }, {
        "id": 50,
        "field": "fst_pkg_time",
        "name": "首包时间",
        "type": "double"
    }, {
        "id": 51,
        "field": "upstream_http_x_info_errCode",
        "name": "域名类型",
        "type": "string"
    }, {
        "id": 52,
        "field": "upstream_response_time",
        "name": "upstream_response_time",
        "type": "double"
    }, {
        "id": 53,
        "field": "file_size",
        "name": "数据元总大小",
        "type": "int"
    }, {
        "id": 54,
        "field": "body_bytes_sent",
        "name": "body_bytes_sent",
        "type": "int"
    }, {
        "id": 55,
        "field": "http_log_variable_41",
        "name": "remote_user",
        "type": "string"
    }, {
        "id": 56,
        "field": "http_log_variable_42",
        "name": "",
        "type": "string"
    }, {
        "id": 57,
        "field": "http_log_variable_43",
        "name": "",
        "type": "string"
    }, {
        "id": 58,
        "field": "http_log_variable_44",
        "name": "",
        "type": "string"
    }, {
        "id": 59,
        "field": "http_log_variable_45",
        "name": "",
        "type": "string"
    }, {
        "id": 60,
        "field": "http_log_variable_46",
        "name": "",
        "type": "string"
    }, {
        "id": 61,
        "field": "http_log_variable_47",
        "name": "",
        "type": "string"
    }, {
        "id": 62,
        "field": "http_log_variable_48",
        "name": "",
        "type": "string"
    }, {
        "id": 63,
        "field": "http_log_variable_49",
        "name": "",
        "type": "string"
    }, {
        "id": 64,
        "field": "http_log_variable_50",
        "name": "",
        "type": "string"
    }, {
        "id": 65,
        "field": "http_log_variable_51",
        "name": "在crt字段中，会依次注入 crt_x对应的带宽数值和请求数值；",
        "type": "string"
    }, {
        "id": 66,
        "field": "http_log_variable_52",
        "name": "data_x对应的带宽数值和请求数值",
        "type": "string"
    }, {
        "id": 67,
        "field": "http_log_variable_53",
        "name": "码率比例系数（H.264/H.265）|265产品类型",
        "type": "string"
    }, {
        "id": 68,
        "field": "http_log_variable_54",
        "name": "视频时长",
        "type": "string"
    }, {
        "id": 69,
        "field": "http_log_variable_55",
        "name": "分辨率",
        "type": "string"
    }, {
        "id": 70,
        "field": "http_log_variable_56",
        "name": "",
        "type": "string"
    }, {
        "id": 71,
        "field": "http_log_variable_57",
        "name": "",
        "type": "string"
    }, {
        "id": 72,
        "field": "domain",
        "name": "请求host",
        "type": "string"
    }, {
        "id": 73,
        "field": "http_log_variable_59",
        "name": "访问addr",
        "type": "string"
    }, {
        "id": 74,
        "field": "http_log_variable_60",
        "name": "Cache的真实层级",
        "type": "string"
    }, {
        "id": 75,
        "field": "http_log_variable_61",
        "name": "",
        "type": "string"
    }, {
        "id": 76,
        "field": "http_log_variable_62",
        "name": "",
        "type": "string"
    }, {
        "id": 77,
        "field": "http_log_variable_63",
        "name": "",
        "type": "string"
    }, {
        "id": 78,
        "field": "http_log_variable_64",
        "name": "",
        "type": "string"
    }, {
        "id": 79,
        "field": "http_log_variable_65",
        "name": "",
        "type": "string"
    }, {
        "id": 80,
        "field": "http_log_variable_66",
        "name": "",
        "type": "string"
    }, {
        "id": 81,
        "field": "http_log_variable_67",
        "name": "",
        "type": "string"
    }, {
        "id": 82,
        "field": "http_log_variable_68",
        "name": "",
        "type": "string"
    }, {
        "id": 83,
        "field": "http_log_variable_69",
        "name": "",
        "type": "string"
    }, {
        "id": 84,
        "field": "http_log_variable_70",
        "name": "",
        "type": "string"
    }];

    return LogTplManageOriginField;
});
